### ISSUE TITLE
Dyno bot died, we need to do something about it

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/JShellBot#39]
Dyno bot has died and does not send responses to commands, this is a big problem as Dyno Bot is vital to our server. A lot of commands help us in providing information without typing long messages. A temporary solution would be to add some of the frequent commands to Together Java Bot.

**Comment by java-coding-prodigy** [comment]
I know that this is not relevant to jshell, but there was no other suitable channel

**Comment by illuminator3** [comment]
Dyno dies regularly, we can't do anything about it. It's going to be back up asap since we aren't the only server using it :)

**Comment by java-coding-prodigy** [comment]
> Dyno dies regularly, we can't do anything about it. It's going to be back up asap since we aren't the only server using it :)

Oh so Dyno is dead throughout discord? I thought it was only our server.

**Comment by java-coding-prodigy** [comment]
Update: Dyno bot is fixed now
